version: "3"
services:
  web:
    image: mongo:latest
    container_name: "web"
    links:
      - db
    networks:
      - net1
  db:
    image: mongo:latest
    container_name: "db"
    command: mongod
    networks:
      - net1
networks:
  net1:
    driver: bridge


