version: "3"
services:
  web:
    build: .
    container_name: "web"
    volumes:
      - .:/web
    ports:
      - "3000:3000"
    tty: true
    networks:
      - net1
  db:
    image: mongo:latest
    container_name: "db"
    command: mongod
    networks:
      - net1
networks:
  net1:
    driver: bridge


